In [1]:
from GetSignal import GetSignal
from Database import Database

In [2]:
signal_name = 'interaction_ratio_alpha_63d_ptx_est_rev_180d'
signal_names = ['interaction_ratio_alpha_63d_ptx_est_rev_180d', 'interaction_diff_squared_alpha_63d_res_ret_vol_63d']

In [3]:
db = Database()

In [4]:
df = GetSignal(db).run(signal_name)
df

              date     requestId  interaction_ratio_alpha_63d_ptx_est_rev_180d
0       2004-01-05  BBG000B9X5K7                                      0.170249
1       2004-01-08  BBG000B9X5K7                                      0.135686
2       2004-01-26  BBG000B9X5K7                                      0.239958
3       2004-02-09  BBG000B9X5K7                                      0.209867
4       2004-04-29  BBG000B9X5K7                                     -0.692655
...            ...           ...                                           ...
2058703 2024-07-02  BBG01LSCLRY5                                     -0.003095
2058704 2024-07-30  BBG01LSCLRY5                                      0.593595
2058705 2024-08-14  BBG01LSCLRY5                                      0.188411
2058706 2024-09-10  BBG01LSCLRY5                                      0.094545
2058707 2024-09-26  BBG01MZQYJF9                                      1.160080

[2058708 rows x 3 columns]

In [5]:
df = GetSignal(db).run(signal_names)
df

signal,date,requestId,interaction_diff_squared_alpha_63d_res_ret_vol_63d,interaction_ratio_alpha_63d_ptx_est_rev_180d
0,2004-01-02,BBG000B9X5K7,88.056791,0.150646
1,2004-01-02,BBG000B9XRY4,634.906649,-0.394673
2,2004-01-02,BBG000B9YHW7,180.541924,0.293854
3,2004-01-02,BBG000B9ZXB4,12.099100,0.066521
4,2004-01-02,BBG000BB1BW1,2.282254,-0.088375
...,...,...,...,...
2067714,2024-10-03,BBG01J9M42H2,463.215854,0.335693
2067715,2024-10-03,BBG01JRQSDB9,484.634248,0.358746
2067716,2024-10-03,BBG01KWR26Q5,1757.265440,-3.811065
2067717,2024-10-03,BBG01LSCLRY5,120.010272,-0.837602
2067718,2024-10-03,BBG01MZQYJF9,1227.952977,1.105736

In [6]:
df = GetSignal(db).run(signal_names, start_date = '2022-01-01', end_date = '2024-12-31')
df

signal,date,requestId,interaction_diff_squared_alpha_63d_res_ret_vol_63d,interaction_ratio_alpha_63d_ptx_est_rev_180d
0,2022-01-03,BBG000B9XRY4,261.624187,0.286332
1,2022-01-03,BBG000B9ZXB4,199.236923,0.173072
2,2022-01-03,BBG000BB34J0,368.246812,-0.154250
3,2022-01-03,BBG000BB4HM6,66.440415,-0.159581
4,2022-01-03,BBG000BB5006,465.623506,0.350722
...,...,...,...,...
378861,2024-10-03,BBG01J9M42H2,463.215854,0.335693
378862,2024-10-03,BBG01JRQSDB9,484.634248,0.358746
378863,2024-10-03,BBG01KWR26Q5,1757.265440,-3.811065
378864,2024-10-03,BBG01LSCLRY5,120.010272,-0.837602
378865,2024-10-03,BBG01MZQYJF9,1227.952977,1.105736

In [7]:
df = GetSignal(db).run(signal_name, refresh_data = True)
df.sort_values(['date', 'requestId']).set_index(['date', 'requestId'])

No new coverage to rebuild for 'interaction_ratio_alpha_63d_ptx_est_rev_180d'. Using repository data only.

                         interaction_ratio_alpha_63d_ptx_est_rev_180d
date       requestId
2004-01-02 BBG000B9X5K7                                      0.150646
           BBG000B9XRY4                                     -0.394673
           BBG000B9YHW7                                      0.293854
           BBG000B9ZXB4                                      0.066521
           BBG000BB1BW1                                     -0.088375
...                                                               ...
2024-10-03 BBG01J9M42H2                                      0.335693
           BBG01JRQSDB9                                      0.358746
           BBG01KWR26Q5                                     -3.811065
           BBG01LSCLRY5                                     -0.837602
           BBG01MZQYJF9                                      1.105736

[2058708 rows x 1 columns]

In [8]:
from google.cloud import bigquery
import pandas as pd

def get_unique_signals_from_daily_ic(project_id='issachar-feature-library', 
                                     dataset_name='wmg', 
                                     table_name='daily_ic2'):
    """
    Fetch all unique signal values from the 'signal' column in the daily_ic table.
    
    Args:
        project_id (str): The Google Cloud project ID.
        dataset_name (str): The BigQuery dataset name.
        table_name (str): The BigQuery table name containing the daily IC results.
    
    Returns:
        list: A list of unique signal names.
    """
    # Create a BigQuery client.
    client = bigquery.Client(project=project_id)
    
    # Construct the query to select distinct signals.
    query = f"""
    SELECT DISTINCT signal
    FROM `{project_id}.{dataset_name}.{table_name}`
    """
    
    # Execute the query.
    query_job = client.query(query)
    
    # Convert the result to a pandas DataFrame.
    df = query_job.to_dataframe()
    
    # Return the unique signals as a list.
    return df['signal'].unique().tolist()

invalid = ['localPrice', 'lastPrice', 'isin', 'si', 'smi_id', 't1_beta_adjusted_log_returns', 'float', 'invest', 'invest_cap', 'invest_cf', 'isin', 'lastPrice', 'localPrice', 'market_sector_des', 't1_beta_adjusted_log_returns', 'ticker_name', 'universe_start_date', 'sm_id']
all_signals = get_unique_signals_from_daily_ic()
all_signals = list(set( [x for x in all_signals if not x in invalid] ))

In [ ]:
from tqdm import tqdm
verbose = False

# Instantiate Database
db = Database(verbose = verbose)

for signal_name in tqdm(all_signals, total = len(all_signals), desc = 'Updating all signals...'):
    try:
        GetSignal(db, verbose = verbose).run(signal_name, refresh_data = True)
    except:
        continue

Updating all signals...:   2%|▏         | 15/865 [03:09<2:31:55, 10.72s/it]

No data found in repository for 'interaction_squared_sum_interaction_sum_res_ret_vol_63d_dd_252d_ulcer_63d'.

Updating all signals...:   5%|▌         | 45/865 [11:49<1:57:34,  8.60s/it]

Signal 'fql_2' not found in lookup table.

Updating all signals...:   9%|▉         | 78/865 [19:19<2:37:43, 12.02s/it]

### Test delete of signal (and refresh)

In [ ]:
db = Database(verbose = True)

signal_name = "interaction_ratio_alpha_63d_ptx_est_rev_180d"
db.delete_signal_from_repository(signal_name)
print(f"Deleted all rows for '{signal_name}' in signal_repository.")

GetSignal(db, verbose = True).run(signal_name, refresh_data = True)